### PR TITLE
added || for ebs.csi.aws.com only

### PR DESCRIPTION
**Pull request by kristianfzr**
The current state does not pick up the EBS volume when created by the csi driver, this is probably due to the kubernetes.io/ in the provisioner statement. It works for aws-ebs as thats how the provisioner is called, but csi is called only by its name without the kubernetes.io in front, if that makes sense.

### CODE REVIEW

**Comment by kristianfzr** [comment]
It seems that it finds the EBS, but that crashes the pod, I am not that familiar with Go, so I cannot debug it. I had to setup everything locally and setup my own docker registry in order not to touch the project. The outcome is this:

`2021/05/25 13:19:45 	=> Volume is not EBS. Ignoring`
`2021/05/25 13:19:45 Cannot find EBS volume associated with : resource name may not be empty`
`panic: runtime error: invalid memory address or nil pointer dereference`
`[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x138651c]`
`goroutine 1 [running]:`
`main.main()`
`	/go/src/github.com/kristiankanchev/kube-tagger/main.go:102 +0x4dc`

**Comment by sergiorua** [comment]
New version being built based on docs found on https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html

It should be ready in the next 30 min

**Comment by kristianfzr** [comment]
Perfect! I will test the env after 30 mins and update you.

**Comment by kristianfzr** [comment]
It seems to crash the pod:
`2021/05/25 19:27:16 	=> Volume  is not of a supported type. Ignoring`
`2021/05/25 19:27:16 Cannot find EBS volume associated with : resource name may not be empty`
`panic: runtime error: invalid memory address or nil pointer dereference`
`[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x138651c]`
`goroutine 1 [running]:`
`main.main()`
`	/go/src/github.com/sergiorua/kube-tagger/main.go:102 +0x4dc`

What I am deploying:
`apiVersion: storage.k8s.io/v1`
`kind: StorageClass`
`metadata:`
 ` name: ebs-sc`
`provisioner: ebs.csi.aws.com`
`volumeBindingMode: Immediate`

And:

`apiVersion: v1`
`kind: PersistentVolumeClaim`
`metadata:`
` name: ebs-claim`
` annotations:`
`    volume.beta.kubernetes.io/additional-resource-tags: kube-tagger=true`
`spec:`
 ` accessModes:`
  `  - ReadWriteOnce`
  `storageClassName: ebs-sc`
  `resources:`
    `requests:`
      `storage: 3Gi`

**Comment by sergiorua** [comment]
Sorry, it's not going to work. It needs more changes and I've been hacking away blind. The CSI driver object is completely different and it won't work with current code. It's probably not a big change but I don't dare making any more changes without access to a EKS cluster with CSI installed.

https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/controller/controller_test.go#L842

**Comment by kristiankanchev** [comment]
I understand and thank you for putting so much effort into this! Im hacking a lot of the stuff myself and I will invest in some Go in order to be prepared in the future. But this tagger in general is great and does the needed as tested for the kubernetes.io/aws-ebs. At some point im sure it will be perfect with the csi driver as well!

**Comment by kristianfzr** [comment]
I understand and thank you for putting so much effort into this! Im hacking a lot of the stuff myself and I will invest in some Go in order to be prepared in the future. But this tagger in general is great and does the needed as tested for the kubernetes.io/aws-ebs. At some point im sure it will be perfect with the csi driver as well!

**Comment by sergiorua** [comment]
@kristianfzr I made some more blind changes, it could potentially work but I'm not going to release them without testing them. If you have the capacity they're in the CSI branch:

https://github.com/sergiorua/kube-tagger/tree/CSI

Do `make run` to test it without having to install it to the cluster.

**Comment by kristianfzr** [comment]
Thanks! I already set an environment that is a copy of what you have and set it as a local helm chart and deploy it through terraform. I can make a few changes locally and update my docker image to include the new changes. That will be tomorrow, I will update here on the status.

**Comment by kristianfzr** [comment]
@sergiorua I did test with the CSI branch. I added a new docker image and pushed it to my registry, created a local helm chart and pointed terraform there. It deployd everything with the correct images and settings but each time I deploy a PVC with the csi provisioner it crashes. I will have to pause on my end for a bit as there are tasks that I need to take care of.

Thank you again!

Log:
`2021/05/26 06:41:40 	=> Volume  is not of a supported type. Ignoring`
`2021/05/26 06:41:40 Cannot find EBS volume associated with : resource name may not be empty`
`panic: runtime error: invalid memory address or nil pointer dereference`
`[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1386b13]`
`goroutine 1 [running]:`
`main.main()`
	`/go/src/github.com/kristiankanchev/kube-tagger/main.go:105 +0xad3`

A tagger that was tested and worked, but had a few bad permissions here and there is this one: https://github.com/mtougeron/k8s-aws-ebs-tagger

**Pull request closed without merging**
